name: Terraform Cloud Run

on:
  workflow_dispatch:


jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    defaults:
      run:
        shell: bash
        working-directory: cloudrun/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write GCP credentials to file
        run: echo "$GOOGLE_CREDENTIALS" > gcp-key.json

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Extract values from terraform.tfvars
        id: tfvars
        run: |
          export PROJECT_ID=$(grep '^project_id' terraform.tfvars | cut -d'"' -f2)
          export REGION=$(grep '^region' terraform.tfvars | cut -d'"' -f2)
          export IMAGE_NAME=$(grep '^image_name' terraform.tfvars | cut -d'"' -f2)
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
          echo "REGION=$REGION" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${PROJECT_ID}/${IMAGE_NAME} ../app      

      - name: Push Docker image
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${PROJECT_ID}/${IMAGE_NAME}
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="image_url=gcr.io/${PROJECT_ID}/${IMAGE_NAME}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_url=gcr.io/${PROJECT_ID}/${IMAGE_NAME}"